### ISSUE TITLE
Unclear error 

### ISSUE THREAD

**Issue by AmdaU** [erietz/ultisnips-vscode#6]
Hi, very cool script!

However, when I try to use it I get the following error:

```
bib.snippets                   -->        bibtex.json                   
coffee.snippets                -->        coffeescript.json             
ruby.snippets                  -->        ruby.json                     
gitcommit.snippets             -->        git-commit.json               
css.snippets                   -->        css.json                      
java.snippets                  -->        java.json                     
Traceback (most recent call last):
  File "/home/amda/.local/bin/ultisnips2vscode", line 28, in <module>
    main()
  File "/home/amda/.local/bin/ultisnips2vscode", line 14, in main
    parser.parse_snippets(verbose=True)
  File "/home/amda/.local/lib/python3.10/site-packages/ultisnips2vscode/UltisnipParser.py", line 112, in parse_snippets
    snippets = self._parse_snippet(scope)
  File "/home/amda/.local/lib/python3.10/site-packages/ultisnips2vscode/UltisnipParser.py", line 89, in _parse_snippet
    line = next(f)
```

The error message doesn't make the problem very clear. I assume it tried to parse something that is not supported by the translation, however, it is unclear which file it fails to parse (doesn't seem to be the java one as removing it completely did not fix the error).

It would be very nice if the script printed which file il will attempt to parse before doing so and possibly give you a clue as to what went wrong!

Thank you!

**Comment by AmdaU** [comment]
😅

**Comment by erietz** [comment]
Hi, sorry I never answered this. Did you determine what caused the error?
